export const routes = {
  home: "/",
  login: "/login",
  daftar: "/daftar",
  dashboard: "/dashboard",
  obat: "/obat",
  kategori: "/kategori",
  supplier: "/supplier",
  pelanggan: "/pelanggan",
  stok: "/stok",
  pembelian: "/pembelian",
  kasir: "/penjualan/kasir",
  penjualan: "/penjualan",
  returPenjualan: "/retur-penjualan",
  resep: "/resep",
  laporan: "/laporan/penjualan",
  notifikasi: "/notifikasi",
  users: "/users",
  pengaturan: "/pengaturan/profil"
} as const;
